sudo: required
dist: trusty
language: python
python:
  # - 2.7
  - "2.7_with_system_site_packages"
branches:
  only:
    - edgarriba-cmake
install:
  - pip install --upgrade numpy
  - pip install catkin-pkg 
  - sudo apt-get install python-opencv -y
  - "bash configure.sh"
  - "mkdir build && cd build && cmake .. && make && cd .."
script: nosetests
