sudo: required
dist: trusty
language: python
python:
  # - 2.7
  - "2.7_with_system_site_packages"
branches:
  only:
    - edgarriba-cmake
install:
  - pip install --upgrade numpy
  - pip install catkin-pkg 
  - sudo apt-get install python-opencv -y
  - "bash configure.sh"
  - "mkdir build && cd build && cmake .. && make && cd .."
  - "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/build/dakotabenjamin/OpenDroneMap/SuperBuild/install/lib"
  - "export PYTHONPATH=$PYTHONPATH:/home/travis/build/dakotabenjamin/OpenDroneMap/SuperBuild/install/lib:/home/travis/build/dakotabenjamin/OpenDroneMap/SuperBuild/install/lib/python2.7/dist-packages:/home/travis/build/dakotabenjamin/OpenDroneMap/SuperBuild/install/lib/python2.7/site-packages:/home/travis/build/dakotabenjamin/OpenDroneMap/SuperBuild/src/opensfm"
script: nosetests
